fix : response api
IMTALabs/english-client pull request #47
Opened 2024-01-27 10:35 UTC by daocuong2306

2024-01-28 09:38 UTC, CongDuongLe commented on src/features/common/reading-slice/index.ts
> +            console.log(action.payload);
log

2024-01-28 09:38 UTC, CongDuongLe commented on src/components/feedback/index.tsx
> +  const [isDisabled, setIsDisabled] = useState(false);
không cần

2024-01-28 09:38 UTC, CongDuongLe commented on src/components/feedback/index.tsx
> +      setIsDisabled(false)
feedback k cần

2024-01-28 09:39 UTC, CongDuongLe commented on src/components/feedback/index.tsx
> +          className="input input-primary w-full my-4 border"
sửa lại feedback

2024-01-28 09:39 UTC, CongDuongLe commented on src/pages/protected/listening/index.tsx
> +      console.log(error);
log

2024-01-28 09:39 UTC, CongDuongLe commented on src/pages/protected/listening/index.tsx
> +    const regex = /^(https?\:\/\/)?(www\.youtube\.com|youtube\.com|youtu\.?be)\/.+$/;
làm gì đây >

2024-01-28 09:40 UTC, CongDuongLe commented on src/pages/protected/reading/index.tsx
>      const limitedText =
3000 kí tự cơ à

2024-01-28 09:40 UTC, CongDuongLe commented on src/pages/protected/reading/result/index.tsx
> +    console.log(markReading );
log

2024-01-28 09:41 UTC, CongDuongLe commented on src/pages/protected/reading/result/index.tsx
> +                            {markReading?.data?.results?.map((item: Question, index: number) => {
sao e không config ở redux mà cứ push cả cái response vào nhỉ ?

2024-01-28 09:41 UTC, CongDuongLe commented on src/pages/protected/reading/result/index.tsx
> +                            {markReading?.data?.results?.map((item: Question, index: number) => {
cần gì ở api này thì set redux state là như thế

2024-01-28 09:41 UTC, CongDuongLe requested changes
rep các comment và sửa lại

2024-01-28 10:04 UTC, daocuong2306 commented on src/pages/protected/listening/index.tsx
> +    const regex = /^(https?\:\/\/)?(www\.youtube\.com|youtube\.com|youtu\.?be)\/.+$/;
cái này có trường hợp youtube nó có đường link đấy anh ạ, hôm qua thử nó phải thêm trường hợp này

2024-01-28 10:04 UTC, daocuong2306 commented on src/pages/protected/reading/index.tsx
>      const limitedText =
tại anh việt muốn 500 từ, mà mình chỉ cho kí tự với cả 500 kí tự nó hơi ít anh ạ

2024-01-28 10:04 UTC, daocuong2306 commented on src/pages/protected/reading/result/index.tsx
> +                            {markReading?.data?.results?.map((item: Question, index: number) => {
oke anh ơi

2024-01-29 08:56 UTC, CongDuongLe approved these changes

2024-01-29 09:01 UTC, merged